all: vnetspec
include .dep

.SUFFIXES: .mli .cmi
.SUFFIXES: .ml .cmx
.SUFFIXES: .mll .ml
.SUFFIXES: .mly .ml

.mli.cmi:
	ocamlopt -c $<

.ml.cmx: 
	ocamlopt $(CFLAGS) -c $(INCLUDEDIR) $<

.mly.ml: 
	ocamlyacc $< 

.mll.ml:
	ocamllex $< 

vnetspec: globals.cmx types.cmx inotify.cmi rspec.cmx operators2.cmx  parser.cmx lexer.cmx process.cmx inotify.cmxa main.cmx
	ocamlopt str.cmxa types.cmx unix.cmxa inotify.cmxa globals.cmx rspec.cmx operators2.cmx process.cmx parser.cmx lexer.cmx main.cmx -o vnetspec

dep:
	ocamldep *.ml > .dep

clean:
	rm -f *.cmi *.cmx
